- id: parameters
  type: ParaNode
  conf:
    ? seed
  inputs: {}
  module: nemo_modules
- id: mc_simulation
  type: SimNode
  conf:
    N_PATHS: 409600
    Y_STEPS: 252
  inputs:
    para_in: parameters.para_out
  module: nemo_modules
- id: data
  type: OptionDataLayerNode
  conf:
    max_len: 12800
    batch_size: 128
    name: data
  inputs:
    sim_iter: mc_simulation.sim_out
  module: nemo_modules
- id: net
  type: OptionPriceNode
  conf:
    hidden: 512
    layers: 6
    name: net
    share_weight: Tying
  inputs:
    x: data.x
  module: nemo_modules
- id: loss
  type: OptionMSELossNode
  conf:
    name: loss
  inputs:
    predictions: net.y_pred
    target: data.y
  module: nemo_modules
- id: train
  type: NemoTrainNode
  conf:
    parameters:
      tensors_to_optimize:
        - loss@loss
      batches_per_step: 1
      stop_on_nan_loss: false
      synced_batchnorm: false
      synced_batchnorm_groupsize: 0
      gradient_predivide: false
      amp_max_loss_scale: 16777216
      reset: false
    check_point:
      load_from_folder: null
      checkpoints_to_keep: 4
      force_load: false
      folder: nemo_log
      epoch_freq: 1
    simple_logger:
      step_freq: 10
      tensors_to_log:
        - loss@loss
    eval_callback:
      eval_step: 50
      eval_tensors:
        - eval_loss@loss
    warmup_policy:
      parameters:
        warmup_steps: 100
        warmup_ratio: null
        total_steps: 1000
        min_lr: 0.000001
      name: CosineAnnealing
    optimizer:
      parameters:
        num_epochs: 10
        lr: 0.001
        betas:
          - 0.9
          - 0.999
        eps: 1e-9
        weight_decay: 0
        amsgrad: false
      name: adam
  inputs:
    loss@loss: loss.loss
    eval_loss@loss: eval_loss.loss
  module: nemo_modules
- id: ""
  type: Output_Collector
  conf: {}
  inputs:
    in1: train.checkpoint_dir
- id: eval
  type: ParaNode
  conf:
    seed: 2
  inputs: {}
  module: nemo_modules
- id: eval_sim
  type: SimNode
  conf:
    N_PATHS: 819200
    Y_STEPS: 252
  inputs:
    para_in: eval.para_out
  module: nemo_modules
- id: eval_data
  type: OptionDataLayerNode
  conf:
    max_len: 1280
    batch_size: 128
    name: data
  inputs:
    sim_iter: eval_sim.sim_out
  module: nemo_modules
- id: eval_net
  type: OptionPriceNode
  conf:
    hidden: 512
    layers: 6
    name: net
    share_weight: Reuse
  inputs:
    x: eval_data.x
    in_nm: net.out_nm
  module: nemo_modules
- id: eval_loss
  type: OptionMSELossNode
  conf:
    name: loss
  inputs:
    predictions: eval_net.y_pred
    target: eval_data.y
  module: nemo_modules
