- id: dataset
  type: OptionDataLayerNode
  conf:
    seed: 2
    N_PATHS: 409600
    Y_STEPS: 252
    max_len: 10000
    batch_size: 128
    name: data
  inputs: {}
  module: nemo_modules
- id: net
  type: OptionPriceNode
  conf:
    hidden: 512
    name: net
    share_weight: Tying
  inputs:
    x: dataset.x
  module: nemo_modules
- id: loss
  type: OptionMSELossNode
  conf:
    name: loss
  inputs:
    predictions: net.y_pred
    target: dataset.y
  module: nemo_modules
- id: train
  type: NemoTrainNode
  conf:
    parameters:
      tensors_to_optimize:
        - loss@loss
      batches_per_step: 1
      stop_on_nan_loss: false
      synced_batchnorm: false
      synced_batchnorm_groupsize: 0
      gradient_predivide: false
      amp_max_loss_scale: 16777216
      reset: false
    check_point:
      load_from_folder: null
      checkpoints_to_keep: 4
      force_load: false
      folder: nemo_log
    simple_logger:
      step_freq: 10
      tensors_to_log:
        - loss@loss
    eval_callback:
      ? eval_step
    warmup_policy: {}
    optimizer:
      parameters:
        num_epochs: 10
        lr: 0.001
        betas:
          - 0.9
          - 0.999
        eps: 1e-9
        weight_decay: 0
        amsgrad: false
        momentum: 0.9
      name: adam
  inputs:
    loss@loss: loss.loss
  module: nemo_modules
- id: ""
  type: Output_Collector
  conf: {}
  inputs:
    in1: train.checkpoint_dir
